contolplane-lb: [contolplane-lb/**]
curl: [curl/**]
deckschrubber: [deckschrubber/**]
docker: [docker/**]
fluentd: [fluentd/**]
github-actions-runner: [github-actions-runner/**]
haproxy: [haproxy/**]
helm: [helm/**]
ipsec: [ipsec/**]
keydb: [keydb/**]
mongodb: [mongodb/**]
mongosqld: [mongosqld/**]
mongosync: [mongosync/**]
nginx-openresty: [nginx-openresty/**]
openvpn: [openvpn/**]
pgbouncer: [pgbouncer/**]
postgresql: [postgresql/**]
reviewdog: [reviewdog/**]
skopeo: [skopeo/**]
sops: [sops/**]
supercronic: [supercronic/**]
tabix: [tabix/**]
tinyproxy: [tinyproxy/**]
vals: [vals/**]
wal-g: [wal-g/**]
wireguard: [wireguard/**]
ytt: [ytt/**]
