name: Renovate

on:
  workflow_dispatch:
  schedule:
      - cron: '0 9 * * 1'

jobs:
  renovate:
    name: "Renovate"
    runs-on: ubuntu-24.04
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Renovate
        uses: renovatebot/github-action@1a96852b0384df1837619d04c60b2d10d1f9ff08 # v46.1.21
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
